name = "WiNDC"
uuid = "699cc7a2-9ea9-42f0-a823-bc8522533664"
authors = ["mitchphillipson <mitch.phillipson@gmail.com>"]
version = "0.1.1"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MPSGE = "d5dc2f44-7ae2-49e9-bc77-b47b6bca565d"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[compat]
CSV = "0.10.15"
DataFrames = "1.7.0"
Downloads = "1.6.0"
FileIO = "1.16.6"
Ipopt = "1.7.1"
JLD2 = "0.5.11"
JuMP = "1.24.0"
MPSGE = "0.5.2"
XLSX = "0.10.4"
ZipFile = "0.10.1"
julia = "1.10.4"
